<a href="https://colab.research.google.com/github/PVNgopal07/Machine-Learning/blob/main/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#1. Perform arithmetic operations on NumPy arrays.

In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print("Array 1 :",a)
print("Array 2 :",b)
print("Addition :",a+b)
print("Subtraction :",a-b)
print("Multiplication :",a*b)
print("Division :",a/b)
print("Floor Division :",a//b)
print("Remainder :",a%b)

Array 1 : [1 2 3 4 5]
Array 2 : [ 6  7  8  9 10]
Addition : [ 7  9 11 13 15]
Subtraction : [-5 -5 -5 -5 -5]
Multiplication : [ 6 14 24 36 50]
Division : [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Floor Division : [0 0 0 0 0]
Remainder : [1 2 3 4 5]


#2. Write a script to compute the mean and standard deviation of a NumPy array.

In [ ]:
c=np.array([1,2,3,4,5])
print("The given Array is :",c)
c1=np.mean(c)
print("Mean :",c1)
c2=np.std(c)
print("Standard Deviation :",c2)

The given Array is : [1 2 3 4 5]
Mean : 3.0
Standard Deviation : 1.4142135623730951


#3. Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [ ]:
d=np.array(range(10,50,5))
print(d)

[10 15 20 25 30 35 40 45]


#4. Reshape the array into a 2x4 matrix.

In [ ]:
d1=np.array([1,2,3,4,5,6,7,8])
print("Array befor :",d1)
d2=d1.reshape(2,4)
print("Array after reshaping :\n",d2)

Array befor : [1 2 3 4 5 6 7 8]
Array after reshaping :
 [[1 2 3 4]
 [5 6 7 8]]


##5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

#a) Extract the sub-matrix containing the last two rows and first two columns.

In [ ]:
print("Matrix :\n", arr)
arr1=arr[1:3,0:2]
print("Sub-Matrix :\n", arr1)

Matrix :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sub-Matrix :
 [[4 5]
 [7 8]]


#b) Replace all elements greater than 4 with 0.

In [ ]:
print("Matrix :\n", arr)
arr[arr>4]=0
print("After Replacing :\n", arr)

Matrix :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
After Replacing :
 [[1 2 3]
 [4 0 0]
 [0 0 0]]


##6. Create two 1D arrays:
• a = np.array([1, 2, 3])

• b = np.array([4, 5, 6])

In [ ]:
 a = np.array([1, 2, 3])
 b = np.array([4, 5, 6])
 print("Array 1 :",a)
 print("Array 2 :",b)

Array 1 : [1 2 3]
Array 2 : [4 5 6]


#• Perform element-wise addition, multiplication, and division.

In [ ]:
n1=np.add(a,b)
print("Addition :",n1)
n2=np.multiply(a,b)
print("Multiplication :",n2)
n3=np.divide(a,b)
print("Division :",n3)

Addition : [5 7 9]
Multiplication : [ 4 10 18]
Division : [0.25 0.4  0.5 ]


##7. Create a random NumPy array of size (4, 4).

In [ ]:
d4=np.random.random((4,4))
print(d4)

[[0.52693921 0.87119807 0.62455194 0.71731497]
 [0.88343032 0.14840963 0.47673656 0.51460817]
 [0.00668967 0.36732285 0.03297338 0.86502133]
 [0.54302544 0.25104828 0.56442377 0.78877756]]


#a) Mean of each column.

In [ ]:
print("Matrix :\n", d4)
d5=np.mean(d4,axis=0)
print("Mean of each column :",d5)

Matrix :
 [[0.52693921 0.87119807 0.62455194 0.71731497]
 [0.88343032 0.14840963 0.47673656 0.51460817]
 [0.00668967 0.36732285 0.03297338 0.86502133]
 [0.54302544 0.25104828 0.56442377 0.78877756]]
Mean of each column : [0.49002116 0.40949471 0.42467141 0.72143051]


#a) Maximum value of the entire array.

In [ ]:
print("Matrix :\n", d4)
d6=np.max(d4)
print("Maximum value of the entire array :",d6)

Matrix :
 [[0.52693921 0.87119807 0.62455194 0.71731497]
 [0.88343032 0.14840963 0.47673656 0.51460817]
 [0.00668967 0.36732285 0.03297338 0.86502133]
 [0.54302544 0.25104828 0.56442377 0.78877756]]
Maximum value of the entire array : 0.8834303208389713


#b) Sum of all elements.

In [ ]:
print("Matrix :\n", d4)
d7=np.sum(d4)
print("Sum of all elements :",d7)

Matrix :
 [[0.52693921 0.87119807 0.62455194 0.71731497]
 [0.88343032 0.14840963 0.47673656 0.51460817]
 [0.00668967 0.36732285 0.03297338 0.86502133]
 [0.54302544 0.25104828 0.56442377 0.78877756]]
Sum of all elements : 8.182471147345886


#8. Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply the result by 2.


In [ ]:
arr = np.array([1, 2, 3, 4])
print("Array :",arr)
arr1=(arr+10)*2
print("After adding 10 to each element and multiplied the result by 2. :",arr1)

Array : [1 2 3 4]
After adding 10 to each element and multiplied the result by 2. : [22 24 26 28]


##9.Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from 1 to 100.

In [ ]:
arr=np.random.randint(1,100,(3,4,5))
print(arr)

[[[80 20 24 43  3]
  [99 21 33 39 43]
  [ 2 51 24 22 67]
  [50 47 72 90 86]]

 [[53 58 94 97 97]
  [55 90 22 93  4]
  [79 25 79  1 53]
  [36 75 26 86 60]]

 [[47 57 19 91  2]
  [41 68 46 91 23]
  [84 39  8  4 91]
  [29 50 77 60 47]]]


#a) Extract the second "layer" (i.e., the second 2D array) in the first dimension.

In [ ]:
print("Matrix :\n", arr)
arr1=arr[1]
print("Second layer :\n", arr1)

Matrix :
 [[[80 20 24 43  3]
  [99 21 33 39 43]
  [ 2 51 24 22 67]
  [50 47 72 90 86]]

 [[53 58 94 97 97]
  [55 90 22 93  4]
  [79 25 79  1 53]
  [36 75 26 86 60]]

 [[47 57 19 91  2]
  [41 68 46 91 23]
  [84 39  8  4 91]
  [29 50 77 60 47]]]
Second layer :
 [[53 58 94 97 97]
 [55 90 22 93  4]
 [79 25 79  1 53]
 [36 75 26 86 60]]


#b) Extract the first two rows and the last three columns from each "layer."

In [ ]:
print("Matrix :\n", arr)
arr2=arr[:,:2,2:]
print("After exracting the first two rows and last three columns from each layer :\n", arr2)

Matrix :
 [[[80 20 24 43  3]
  [99 21 33 39 43]
  [ 2 51 24 22 67]
  [50 47 72 90 86]]

 [[53 58 94 97 97]
  [55 90 22 93  4]
  [79 25 79  1 53]
  [36 75 26 86 60]]

 [[47 57 19 91  2]
  [41 68 46 91 23]
  [84 39  8  4 91]
  [29 50 77 60 47]]]
After exracting the first two rows and last three columns from each layer :
 [[[24 43  3]
  [33 39 43]]

 [[94 97 97]
  [22 93  4]]

 [[19 91  2]
  [46 91 23]]]


#c) Replace all elements divisible by 3 with -1.

In [ ]:
arr1=np.random.randint(1,100,(3,4,5))
print("Matrix :\n", arr1)
arr1[arr1%3==0]=-1
print("After replacing all elements divisible by 3 with -1 :\n", arr1)

Matrix :
 [[[42  1 57 88 41]
  [84 65 42 97 56]
  [64 69 94 44 27]
  [45 27 53 98 51]]

 [[63 59 68 68 29]
  [ 4 96 34 75 80]
  [99 17 29 40 84]
  [ 6 45 53 74 24]]

 [[71  2 47  8 32]
  [ 3 12 55 49 83]
  [ 8 27 77 83 85]
  [73 42 75 16 14]]]
After replacing all elements divisible by 3 with -1 :
 [[[-1  1 -1 88 41]
  [-1 65 -1 97 56]
  [64 -1 94 44 -1]
  [-1 -1 53 98 -1]]

 [[-1 59 68 68 29]
  [ 4 -1 34 -1 80]
  [-1 17 29 40 -1]
  [-1 -1 53 74 -1]]

 [[71  2 47  8 32]
  [-1 -1 55 49 83]
  [ 8 -1 77 83 85]
  [73 -1 -1 16 14]]]


##10. Work with broadcasting and advanced operations in NumPy.

Create a NumPy array arr of shape (3, 3) with random integers between 1 and 20.
Perform the following:

In [ ]:

arr = np.random.randint(1, 21,size=(3, 3))
print(arr)

[[ 2  5 19]
 [12  2  6]
 [10 11 15]]


#a) Subtract the mean of each row from its respective elements (row-wise normalization).

In [ ]:
print("Matrix :\n", arr)
arr1=arr-arr.mean(axis=1,keepdims=True)
print("After subtracting the mean of each row from its respective elements :\n", arr1)

Matrix :
 [[ 2  5 19]
 [12  2  6]
 [10 11 15]]
After subtracting the mean of each row from its respective elements :
 [[-6.66666667 -3.66666667 10.33333333]
 [ 5.33333333 -4.66666667 -0.66666667]
 [-2.         -1.          3.        ]]


#b) Create a new array by squaring all the elements in arr.

In [ ]:
print("Matrix :\n", arr)
arr2=np.square(arr)
print("After squaring all the elements in arr :\n", arr2)

Matrix :
 [[ 2  5 19]
 [12  2  6]
 [10 11 15]]
After squaring all the elements in arr :
 [[  4  25 361]
 [144   4  36]
 [100 121 225]]


#c) Find the indices of the top 3 maximum values in the entire array.

In [ ]:
flat_arr1 = arr1.flatten()
top_3_indices = np.argpartition(flat_arr1, -3)[-3:]
row_indices, col_indices = np.unravel_index(top_3_indices, arr1.shape)
print("Indices of top 3 maximum values:")
for i in range(3):
    print(f"Value: {arr1[row_indices[i]][col_indices[i]]}, Index: ({row_indices[i]}, {col_indices[i]})")

Indices of top 3 maximum values:
Value: 16, Index: (0, 0)
Value: 20, Index: (2, 1)
Value: 20, Index: (0, 1)
